version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - "1337:80"
    depends_on:
      - web
    volumes:
      - type: bind
        source: /srv/project  # here is where the static files for the server get stored, if you change this one, change the ones below as well
        target: /home/project/static
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  rabbitmq:
    image: rabbitmq:3.11-alpine
    container_name: rabbitmq
    env_file:
      - ./.env
    ports:
      - '5672:5672'
      - '15672:15672'
  celery:
    build: .
    command: celery -A MainApp worker -l info
    volumes:
      - type: bind
        source: /srv/project  # static files directory binding
        target: /home/project/static
    env_file:
      - ./.env
    depends_on:
      - rabbitmq
  web:
    build: .
    command: gunicorn Project.wsgi:application --bind 0.0.0.0:8000
    container_name: django_web
    environment:
      - DATABASE_URL
    volumes:
      - type: bind
        source: /srv/project  # static files directory binding
        target: /home/project/static
    expose:
      - 8000
    depends_on:
      - db
      - rabbitmq
      - celery
    env_file:
      - ./.env


volumes:
  postgres_data: